### ISSUE TITLE
Проблема со ссылками

### ISSUE THREAD

**Issue by Hibin** [chipchick21/diploma-js#10]
Загрузил картинку, написал, нарисовал.
Открыл в новом инкогнито-окне.
В первом окне загрузил новую картинку, ссылка сменилась.
Решил в этом же, первом окне, вернуться, перешел по старой ссылке.

Ожидание: увидеть прежнюю картинку со старыми комментами и рисунками.
Реальность: остается новая картинка, ни комментов, ни рисунков.

**Comment by chipchick21** [comment]
исправил.
на локальном сервере проверил данный сценарий и подобные, подгружает те сессии что и должен
