### ISSUE TITLE
Объединить

### ISSUE THREAD

**Issue by Hibin** [chipchick21/diploma-js#11]
https://github.com/chipchick21/diploma-js/blob/418a38aeaf65faa018df792e69cd2876e554afad/js/comments.js#L70-L74

https://github.com/chipchick21/diploma-js/blob/418a38aeaf65faa018df792e69cd2876e554afad/js/comments.js#L82-L86

В этих и аналогичных местах, один раз написать тип переменной (let/const), затем через  запятую и с новой строки перечислить все переменные.

**Comment by chipchick21** [comment]
сделал, но есть вопрос linter от airbnb ругается на такое исполнение const/let переменных, и предлагает все же выполнять их через ; и const в каждой переменной, так вот такое исполнение это просто обговаривается в codestyle команды/проекта , или есть другое требование

**Comment by Hibin** [comment]
Скорее первое, стиль кодирования в командке. Точно не скажу, но это должно настраиваться и в linter-е, чтобы не было ошибок.
